apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::<ACCOUNT_ID>:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1RY9GEWGF374B
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<ACCOUNT_ID>:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-08T16:38:30Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1726"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 7f7a6e74-d28c-4a8c-bdcd-7749a2668460
